# Generated by Django 3.1.6 on 2021-02-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='documents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
