# Generated by Django 3.1.6 on 2021-02-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210216_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_dis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
