# Generated by Django 3.1.6 on 2021-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
