# Generated by Django 3.1.6 on 2021-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userdetail_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='timestmap',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
