# Generated by Django 3.1.6 on 2021-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210219_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='work',
            field=models.ManyToManyField(blank=True, null=True, to='core.Service'),
        ),
    ]
