# Generated by Django 3.1.6 on 2021-02-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210219_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='work',
            field=models.ManyToManyField(to='core.Service'),
        ),
    ]
