# Generated by Django 3.1.6 on 2021-02-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210219_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='timestmap',
            new_name='timestamp',
        ),
    ]
